### ISSUE TITLE
Can you add documentation in readme to use theme color or fonts?

### ISSUE THREAD

**Issue by ccprogrammer** [EmadBeltaje/flutter_getx_template#14]
i want to use the theme that you have made but the design i was working with have a complex design and it's difficult to use the theme since if i hardcode the TextStyle or color i can just copy it from figma design

**Comment by EmadBeltaje** [comment]
i will consider adding a separate readme for the theme but i think its simple to use, you only have to **specify colors in the light/dark colors.dart and fonts sizes in myfonts.dart**, and if you mean that your design has too many colors consider using **theme extension**, for example i needed to use it in my repository so you will find example also for it.

**Comment by ccprogrammer** [comment]
yes sometimes in the design i find many fontstyle then i just confused where to put it in the theme, it's my lack of knowledge about the use of theme. btw your code is amazing

**Comment by EmadBeltaje** [comment]
thank you buddy, in your case, i have some advices

- focus on colors only (I mean lets say in **myfonts.dart** you said that font size of displaySmall = 16) but in your design its sometimes 15 or any other value you just can do it like this ```dart theme.textTheme.displaySmall.copyWith(fontSize: 15)``` same for font weight and other values the only big deal in theme is colors, because when you switch theme you want the colors to change not the sizes
- lets say its a mess here so your **displaySmall** color is **Black** but in some cases in design its grey, well in this case its not recommended to use **copyWith** because you will hard code the (grey color for example) but when you switch theme it will remain **grey** and will not switch as intended, so the better thing to do is using theme extension (make custom theme for those small things that are different from any other parts of design) in modern designs you should not face this kind of problems but custom extensions are there to solve this specific problem and if you face any hardness I am here to help 🍁

**Comment by ccprogrammer** [comment]
thank you it helped me, Jazzakallah Khairan ya akhi
